import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  Boxes,
  ChartColumn,
  ChartColumnBig,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock3,
  CircleHelp,
  Eye,
  FileText,
  LayoutDashboard,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPinned,
  Menu,
  MessageSquareQuote,
  Minus,
  Package,
  Package2,
  Phone,
  Plus,
  Search,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tags,
  Truck,
  UserRound,
  Users,
  WalletCards,
  X,
} from 'lucide-angular';
import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withComponentInputBinding(),
      withInMemoryScrolling({ scrollPositionRestoration: 'top' })
    ),
    provideHttpClient(withInterceptors([authInterceptor, errorInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertTriangle,
        ArrowLeft,
        ArrowRight,
        ArrowUpRight,
        Bell,
        Boxes,
        ChartColumn,
        ChartColumnBig,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        Clock3,
        CircleHelp,
        Eye,
        FileText,
        LayoutDashboard,
        LogOut,
        Mail,
        MapPinned,
        Menu,
        MessageSquareQuote,
        Minus,
        Package,
        Package2,
        Phone,
        Plus,
        Search,
        Shield,
        ShieldCheck,
        ShoppingBag,
        SlidersHorizontal,
        Sparkles,
        Star,
        Tags,
        Truck,
        UserRound,
        Users,
        WalletCards,
        X,
      }),
    ),
  ],
};
